DROP TABLE IF EXISTS CASCADE
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  price INTEGER NOT NULL,
  calories INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL,
  quantity INTEGER,
  picture VARCHAR(255) NOT NULL
);
